### ISSUE TITLE
Is there a way to make the mint address ends with 'pump'?

### ISSUE THREAD

**Issue by ligulfzhou** [bilix-software/pump-fun-token-launcher#2]
Your code works perfectly fine. thanks.

but when we go through the mint addresses on pump.fun, most of them end with 'pump'.

use 
>    const mint = Keypair.generate();

will likely not generate a mint address ends with 'pump'.

i wonder if there is away except by brutal force.

**Comment by bilix-software** [comment]
You can generate one and use it instead of the random one yes. See my library here for example:
https://github.com/bilix-software/solana-vanity-generator

**Comment by 0xwckd** [comment]
I mined a vanity keypair ends with 'pump' and launched the token successfully, but the token cannot be viewed on pump.fun. Any idea?
